### ISSUE TITLE
Users do not seem to be set available per default

### ISSUE THREAD

**Issue by grandeljay** [grandeljay/discord-availability#14]

**Comment by grandeljay** [comment]
I just tried it again and it seems to work. Did you maybe remove this feature to get the bot running? I have the feeling that the live bot's code is very different from the code here.

@jtrees could you do a diff or something?

**Comment by jtrees** [comment]
Here's the diff: https://github.com/grandeljay/discord-availability/compare/bae711f815013b81cd4c970276efdf9a6dcd9581..main

As I've mentioned several times: I submitted all changes as upstream PRs.

I'll switch to `main` soon though.
